
name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build Docker image
        run: docker build -t myapp:latest .
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Run tests
        run: docker run myapp:latest pytest
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy application
        run: ./scripts/deployment_script.sh
