
stages:
  - build
  - test
  - deploy

build:
  script:
    - docker build -t myapp:latest .

test:
  script:
    - docker run myapp:latest pytest

deploy:
  script:
    - ./scripts/deployment_script.sh
