
pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                sh 'docker build -t myapp:latest .'
            }
        }
        stage('Test') {
            steps {
                sh 'docker run myapp:latest pytest'
            }
        }
        stage('Deploy') {
            steps {
                sh './scripts/deployment_script.sh'
            }
        }
    }
    post {
        failure {
            sh './scripts/rollback_script.sh'
        }
    }
}
